saleor_theme_kotynkova/urls.py
from django.conf.urls import url
from . import views

app_name = 'theme_kotynkova'

urlpatterns = [
    url(r'^(?P<product_id>[0-9]+)/render-image/$',
        views.render_product_image, name="render_product_image"),
    url(r'^(?P<product_id>[0-9]+)/render-thumb/$',
        views.render_product_thumb, name="render_product_thumb"),
    url(r'^(?P<product_id>[0-9]+)/render-details/$',
        views.render_product_details, name="render_product_details"),
    url(r'^create-reservation/$',
        views.create_reservation, name='create_reservation'),
    url(r'^remove-reservation/$',
        views.remove_reservation, name='remove_reservation'),
    url(r'reservation/(?P<slug_id>[a-z0-9-_]+?)/$',
        views.reservation_details, name='reservation_details'),
    url(r'(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/reservation/$',
        views.reserve_picture, name='reserve_picture'),
]

saleor_theme_kotynkova/templates/product/_fullscreen_products.html
{% load i18n %}
{% load staticfiles thumbnail saleor_ext %}

<style type="text/css">
.product-list .object-image img {
    height: 100vh;
    width: auto;
    margin: 0 auto;
}
.info-object {
    display: block;
    opacity: 1;
    transition: all 0.5s ease;
    text-align: left;
}
.btn-load {
    visibility: hidden;
}
#pictureModalFullscreen .modal-body img {
    height: 88vh;
    width: auto;
}
.categories .container-fluid {
    padding: 37px 0px;
    padding-top: 80px;
}
.categories .container-fluid .all-images {
    height: 70vh;
    overflow-y: scroll;
    overflow-x: hidden;
    width: 100%;
    padding-left: 9vw;
    padding-right: 9vw;
}
.categories .top-panel {
    padding-top: 20px;
    padding-bottom: 70px;
}
.categories .container-fluid .all-images .thumb-item {
    margin-bottom: 0;
    padding: 2px;
    cursor: pointer;
}
.categories .container-fluid .all-images .thumb-item img {
    width: 100%;
    height: auto;
}
.categories .container-fluid .all-images .thumb-item.active img {
    -webkit-filter: grayscale(100%);
    filter: grayscale(100%);
}
.btn-categories .arrow {
    border-color: #fff;
}
.object-image.slick-slide {
    background-image: url(/static/css/ajax-loader.gif);
    background-repeat: no-repeat;
    background-position: 50% 40%;
    height: 100vh;
}
.main-images-preview .slick-list {
    background-image: none;
}
.btn-open-panel .btn-title {
    box-shadow: 0px 0px 1px #000000;
}
.search-tab .product-filters .btn-order {
    width: 141px;
    margin-left: 4px;
    height: 25px;
    margin-top: -15px;
    padding: 0px 15px;
}
.categories .show-filters.btn.btn-order {
    display: none;
}

@media screen and (max-width: 1300px) {
    .product-list .object-image img.wide-image {
        width: 100vw;
        height: auto;
    }
}
@media screen and (max-width: 600px) {
    .categories .top-panel {
        padding-top: 0px;
        padding-bottom: 250px;
    }
    .search-tab .product-filters .btn-order {
        margin-top: 5px;
        width: auto;
    }
    .categories .container-fluid .all-images {
        height: 60vh;
        margin-top: 50px;
    }
    .categories .top-panel .close {
        display: none;
    }
    .btn-open-panel.more-info {
        display: none;
    }
    .object-detail.more-info-opened .panel-more-info {
        right: 0!important;
        width: 100%;
    }
    .object-detail.more-info-opened .main-images-preview .slick-next {
        right: 0!important;
    }
    .product-list {
        padding: 0;
    }
    .row {
        margin: 0;
    }
    .btn-categories {
        width: 100%;
        z-index: 999;
        left: 0;
    }
    .object-detail.categories-opened.search-tab-opened .btn-categories {
        left: 0;
    }
    .btn-fullscreen {
        display: none;
    }
    button.slick-arrow {
        top: 150px;
        width: 25px;
        height: 25px;
    }
    .slick-arrow.slick-prev {
        left: 5px!important;
    }
    .slick-arrow.slick-next {
        right: 5px!important;
    }
    .slick-arrow.slick-prev:before,
    .slick-arrow.slick-next:before {
        border-width: 0 1px 1px 0!important;
        padding: 6px!important;
    }
    .categories .top-panel {
        display: none;
    }
    .categories .show-filters.btn.btn-order {
        margin-top: 30px;
        display: inline;
    }
    .object-detail.categories-opened.search-tab-opened .search-tab {
        width: 100%;
    }
}
</style>

<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-select.min.js' %}"></script>

<div class="object-detail more-info-opened search-tab-opened" slick-active-index="">
    <script type="text/javascript">
        function get_product_image(product_url, element) {
            $.ajax({    
                url: product_url,
                success: function(data) {
                    $('.object-image.slick-slide.slick-current.slick-active').html(data);
                    $('#pictureModalFullscreen .modal-body').html(data);
                }
            });
        };
        function get_product_details(product_url) {
            $.ajax({
                url: product_url,
                success: function(data) {
                    $('.panel-more-info').html(data);
                }
            });
        };
    </script>
    <div class="row">
        <!-- <h1>{{ object.translation.title }}</h1> -->
        <div class="col-xs-12 padding-none main-images-preview">
            {% for product, available in picture_list %}
            <div class="object-image" data-picture-id="{{ product.id }}" data-slick-index="{{ forloop.counter0 }}" onclick="get_product_image('{% url 'theme_kotynkova:render_product_image' product_id=product.id %}');get_product_details('{% url 'theme_kotynkova:render_product_details' product_id=product.id %}');">
            </div>
            {% endfor %}
        </div>
        {% if nothing_found != True %}
        <div class="btn-fullscreen">
            <span class="btn-fullscreen" data-toggle="modal" data-target="#pictureModalFullscreen"></span>
        </div>
        {% endif %}
        <div class="btn-categories">
            <span class="title">
                {% trans "Displayed" %} <span>{{ picture_list|count_products }} {{ count_products }}</span>
            </span>
            <span class="arrow"></span>
        </div>
        <div class="categories">
            <div class="container-fluid">
                <button class="show-filters btn btn-order">{% trans "Show filters" %}</button>
                <div class="top-panel">
                    <span class="close">×</span>
                    <div class="search-tab">
                    {% include "product/_filters.html" %}
                    </div>
                </div>
                <div class="row all-images">
                {% for product, available in picture_list %}
                    <div class="col-md-1 col-4 thumb-item" product-id="{{ product.id }}" data-product-id="{{ product.id }}">
                        {% thumbnail product.get_first_image.image "125x125" format="PNG" crop="center" as image %}
                        <img src="{{ image.url }}">
                        {% endthumbnail %}
                    </div>
                {% endfor %}
                {% if nothing_found == True %}
                    <p>{% trans "Sorry, no matches found for your request." %}</p>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% if nothing_found != True %}
    <div class="btn-open-panel more-info">
        <span class="open"></span>
        <span class="btn-title"></span>
    </div>
    <div class="panel-more-info">
        <span class="close">×</span>
    </div>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="pictureModalFullscreen" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
jQuery(function($) {
    setTimeout(function(){
        if (window.location.hash == "#show-all-pictures") {
            $(".object-detail").toggleClass("categories-opened");
        }
    }, 200);
    $(".categories .show-filters").click(function(){
        $(".categories .top-panel").toggle();
    });
    $(".main-images-preview").slick({
        infinite: false,
        slidesToShow: 1,
        slidesToScroll: 1,
        dots: false,
        lazyLoad: 'ondemand',
    });
    $(function() {
        // toggle class more info
        $(".btn-open-panel").click(function(){
            $(".object-detail").toggleClass("more-info-opened");
        });
        $(".panel-more-info .close").click(function(){
            $(".object-detail").removeClass("more-info-opened");
        });

        // click hide categories
        $(".object-image").click(function(){
            $(".object-detail").removeClass("categories-opened");
        });

        // toggle class on catgories
        $(".btn-categories").click(function(){
            $(".object-detail").toggleClass("categories-opened");
        });
        $(".categories .top-panel .close").click(function(){
            $(".object-detail").toggleClass("categories-opened");
        });

        // fix slick id
        $(".maincontent").attr("slick-active-index", $(".slick-current.slick-active").attr("data-slick-index"));
        
        // go to proper slide
        if (window.location.hash.replace("#/","").indexOf("slick-slide-") >= 0 ) {
            var ID = window.location.hash.replace("#slick-slide-","");
            var index = $(".slick-slide[data-picture-id='" + ID + "']").attr("data-slick-index");
            $('.main-images-preview').slick("slickGoTo", index);
        }

        // set id
        function setImageIdToUrl() {
            window.location.hash = "slick-slide-"+$(".slick-current.slick-active").attr("data-picture-id");
        }

        // fix Wide picture
        function fixWidePicture(element) {
            var image = new Image();
            image.src = element.attr("src");
            width = image.naturalWidth;
            height = image.naturalHeight;
            setTimeout(function(){
                if (width - height >= 0) {
                    $(".slick-current.slick-active .project-image").addClass("wide-image");
                }
                $(".slick-current.slick-active").css("background-image", "none");
                if ($(document).width() <= 600) {
                    $(".panel-more-info").css("top", $(".slick-current.slick-active .project-image").height());
                }
            }, 200);
        }

        // set title to btn-title
        function setTitle() {
            $(".btn-open-panel .btn-title").text($(".panel-more-info .info-object h2").text());
        }
        
        $('.slick-current.slick-active').trigger('click');
        $(".all-images .thumb-item[data-product-id='" + window.location.hash.replace("#slick-slide-","") + "']").addClass("active");

        // info inner content, btn afterChange and Wide picture
        $('.main-images-preview').on('afterChange', function(event, slick, currentSlide, direction){
            $('.slick-current.slick-active').trigger('click');
            setImageIdToUrl();
            $(".all-images .thumb-item").removeClass("active");
            $(".all-images .thumb-item[data-product-id='" + window.location.hash.replace("#slick-slide-","") + "']").addClass("active");
            setTimeout(function(){
                setTitle();
            }, 300);
            setTimeout(function(){
                fixWidePicture($(".slick-current.slick-active .project-image"));
            }, 700);
        });

        function goToSlide(ID) {
            $(".object-detail").removeClass("categories-opened");
            var index = $(".slick-slide[data-picture-id='" + ID + "']").attr("data-slick-index");
            $('.main-images-preview').slick("slickGoTo", index);
        }
        
        // set thumbs go to slide
        setTimeout(function(){
            $(".categories .all-images .thumb-item img").click(function(){
                goToSlide($(this).parent().attr("data-product-id"));
            });
            setTitle();
        }, 1000);

        $(document).mouseup(function(e){
            var container = $(".categories .col-12.col-md-2.filter-option");
            if (!container.is(e.target) && container.has(e.target).length === 0) 
            {
                if ($(".btn-group.bootstrap-select.show-tick").hasClass("open")) {
                    $(".btn-group.bootstrap-select.show-tick.open").trigger("click");
                }
            }
        });

        // arrows
        $(document).keydown(function(e){
          if (e.keyCode == 37) { 
            $(".object-detail .slick-prev.slick-arrow").trigger("click");
          }
        });
        $(document).keydown(function(e){
          if (e.keyCode == 39) { 
            $(".object-detail .slick-next.slick-arrow").trigger("click");
          }
        });

        // auto hide panels
        if ($(document).width() >= 600) {
            function hideInfoPanel() {
                infoTimeOut = setTimeout(function(){
                    $(".object-detail").removeClass("more-info-opened");
                }, 4000);
            }
            hideInfoPanel()
            $(".panel-more-info").mouseover(function(){
                $(function(){
                    clearTimeout(infoTimeOut);
                });
            });
        } 
    });
});
</script>

saleor_theme_kotynkova/templates/product/_product_list_banner.html
{% load bootstrap_field from bootstrap4 %}
{% load build_absolute_uri from urls %}
{% load get_object_properties from attributes %}
{% load get_thumbnail from product_images %}
{% load i18n %}
{% load markdown from markdown %}
{% load placeholder thumbnail %}
{% load staticfiles %}
{% load taxed_prices %}

<style type="text/css">
{% for product in products %}
{% thumbnail product.get_first_image.image "x900" crop="center" format="PNG" as product_image %}
.slick-banner-images .banner-item.item-{{ product.id }} {
  background-image: url(/static/images/logo-kotynkova.png), url("/static/images/front_banner_layer_full.png"), url("{{ product_image.url }}");
}
{% endthumbnail %}
{% endfor %}
.slick-banner-images .banner-item {
    background-position: 50% 14px, 92% 100%, top!important;
}
.slick-banner-images .banner-item {
    height: 60vh;
}
.slick-banner-images .banner-item:not(.active) {
    visibility: hidden;
}
.slick-banner-images .banner-item.visible {
    visibility: visible!important;
}

.slick-banner-images .banner-item > .container {
    position: absolute;
    bottom: 0px;
    left: none;
    right: none;
    padding-right: 3vw;
    padding-top: 30px;
    max-width: 100vw;
    bottom: 40px;
}
.slick-banner-images .banner-item .item-info h3 {
    margin-top: 0px;
    font-size: 13px;
    font-weight: bold;
    font-family: Lato,sans-serif;
    text-transform: uppercase;
    line-height: 14px;
}
.slick-banner-images .banner-item .item-info a {
    color: #000;
}
.slick-banner-images .banner-item .item-info a.btn-order {
    width: 100%;
}
.slick-banner-images .banner-item .item-info .format {
    display: block;
    font-size: 12px;
    float: left;
}
.slick-banner-images .banner-item .item-info .status {
    display: block;
    margin-top: 0px;
    font-size: 11px;
}
.slick-banner-images .banner-item .item-info div {
    padding-right: 5px;
}
.slick-banner-images .btn-order:last-child {
    margin-top: 5px;
}
.slick-banner-images button.slick-arrow {
    top: 25vh;
}
.slick-banner-images .slick-prev {
    left: 35px!important;  
}
.slick-banner-images .slick-next {
    right: 35px!important;  
}
.slick-banner-images .slick-dots {
    bottom: 8.3vw;
    left: 17vw;
    width: 82vw;
}
.slick-banner-images .slick-dots li button:before {
    font-size: 27px;
    color: #fff;
    opacity: .5;
}
.slick-banner-images .slick-dots li.slick-active button:before {
    color: #fff;
    opacity: 1;
}
</style>
<link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="/static/js/slick.min.js"></script>

<div class="slick-banner-images">
  {% for product in products %}
  <div class="banner-item item-{{ product.id }} {% if forloop.first %}active{% endif %}" onclick="window.location.href='{% url 'product:category' slug=product.category.slug category_id=product.category.id %}#slick-slide-{{ product.id }}';">
    <div class="container">
      <div class="item-info">
        <div class="row">
        <div class="col-lg-2 offset-lg-8">
          <a href="{% url 'product:category' slug=product.category.slug category_id=product.category.id %}#slick-slide-{{ product.id }}">
            <h3>{{ product.translated }}</h3>
          </a>
          {% for attribute, value in product.get_product_attributes.items %}
          {% if attribute.slug == 'format' %}
              <span class="format">{{ value.translated }}{% if product.variants.count != 1%},&nbsp;{% endif %}</span>
          {% endif %}
          {% endfor %}
          {% for variant in product.variants.all %}
              {% if not variant.name == 'originál' %}
              <span class="format{% if not variant.is_in_stock %} not-in-stock{% endif %}">{{ variant.name }}{% if not forloop.last %},&nbsp;{% endif %}</span>
              {% endif %}
          {% endfor %}
        </div>
        <div class="col-lg-1">
          <a class="btn btn-order" href="{% url 'product:category' slug=product.category.slug category_id=product.category.id %}#slick-slide-{{ product.id }}">{% trans "View" %}</a>
        </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<script type="text/javascript">
jQuery(function($) {
  $(".slick-banner-images").slick({
    infinite: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    dots: true,
    lazyLoad: 'ondemand',
  });
  setTimeout(function(){
    $(".slick-banner-images .banner-item").addClass("visible");
  }, 500);
});
</script>

saleor_theme_kotynkova/templates/product/_product_list_grid.html
{% load i18n %}
{% load staticfiles %}
{% load taxed_prices %}
{% load get_thumbnail from product_images %}
{% load placeholder %}
{% load thumbnail %}

<div class="picture-list">
  <div class="row">
    {% for product in products %}
    <div class="list-item col-md-4">
      <a href="{% url 'product:category' slug=product.category.slug category_id=product.category.id %}#slick-slide-{{ product.id }}">
        {% thumbnail product.get_first_image.image "520x270" format="PNG" crop="center" as image %}
          <img class="lazyload lazypreload" src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}">
        {% endthumbnail %}
      </a>
      <div class="col-6 desc">
        <h4>{{ product.translated }}</h4>
        {% for attr in product.attributes.all %}
        {% if attr.assignment.attribute.slug == 'format' %}
          {% for val in attr.values.all %}
            <span class="format">{{ val }}</span><br/>
          {% endfor %}
        {% endif %}
        {% endfor %}
        {% for variant in product.variants.all %}
            {% if not variant.name == 'originál' %}
            <span class="format{% if not variant.is_in_stock %} not-in-stock{% endif %}">{{ variant.name }}{% if not forloop.last %},{% endif %}</span>
            {% endif %}
        {% endfor %}
      </div>
      <div class="col-6 desc">
        <a class="btn btn-order" href="{% url 'product:category' slug=product.category.slug category_id=product.category.id %}#slick-slide-{{ product.id }}">{% trans "View" %}</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

saleor_theme_kotynkova/templates/product/details.html
{% extends "product/modal.html" %}

{% load bootstrap_field from bootstrap4 %}
{% load build_absolute_uri from urls %}
{% load get_object_properties from attributes %}
{% load get_thumbnail from product_images %}
{% load i18n %}
{% load markdown from markdown %}
{% load placeholder %}
{% load staticfiles thumbnail %}
{% load taxed_prices %}
{% load render_bundle from webpack_loader %}
{% get_current_language as LANGUAGE_CODE %}

{% block extra_styles %}
body.modal-open > .modal-close {
    left: unset;
    right: 82.0%;
    opacity: 0.8;
    display: block;
}
.preloader {
    background: url(https://thumbs.gfycat.com/BriefDescriptiveIcterinewarbler-size_restricted.gif);
    background-size: 45%;
    background-attachment: fixed;
    position: absolute;
    width: 100%;
    background-repeat: no-repeat;
    height: 100%;
    background-color: #000;
    z-index: 150;
    background-position: center;
}
.modal.in .row {
    margin: 0;
    margin-top: 15px;
}
.row.product {
    visibility: hidden;
}
.modal.in .variant-picker__label {
    display: none;
}

.cart-dropdown.d-none.show,
.cart__icon.hover {
    z-index: 400;
}
.fixed-bottom, .fixed-top {
    z-index: 1080;
}
.btn.primary {
    text-decoration: none;
}
{% endblock %}

{% block modal_content %}
  <div class="preloader">
  </div>
  {% if not is_visible %}
    <div class="alert alert-warning" role="alert">
      {% blocktrans trimmed with date=product.available_on|date context "Product details text" %}
        <strong>Warning!</strong>
        You are previewing a product that will become visible on <strong>{{ date }}</strong>.
      {% endblocktrans %}
    </div>
  {% endif %}
  <div class="row product">
    <script type="application/ld+json">{{ json_ld_product_data|safe }}</script>
    <div class="col-md-5 col-12 product__gallery">
      {% with images=product_images %}
        {% if images %}
          <div id="carousel-example-generic" class="carousel slide">
            <div class="carousel-inner" role="listbox">
              {% for image in images %}
                <div class="carousel-item{% if forloop.first %} active{% endif %}">
                  {% thumbnail image.image "x740" as detail_image %}
                  <img src="{{ detail_image.url }}">
                  {% endthumbnail %}
                </div>
              {% endfor %}
            </div>
            {% if images|length > 1 %}
              <a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
                <svg data-src="{% static "images/gallery-arrow.svg" %}" />
              </a>
              <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
                <svg data-src="{% static "images/gallery-arrow.svg" %}" />
              </a>
            {% endif %}
            <ol class="carousel-indicators d-none d-md-block">
              {% for image in images %}
                {% if images|length > 1 %}
                  <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"{% if forloop.first %} class="active"{% endif %}>
                    <img data-src="{% get_thumbnail image.image method="crop" size=60 %}"
                         data-srcset="{% get_thumbnail image.image method="crop" size=60 %} 1x, {% get_thumbnail image.image method="crop" size=120 %} 2x"
                         alt=""
                         class="lazyload lazypreload"
                         src="{% placeholder size=60 %}">
                  </li>
                {% endif %}
              {% endfor %}
            </ol>
          </div>
        {% else %}
          <img data-src="{% placeholder size=540 %}"
               data-srcset="{% placeholder size=540 %} 1x, {% placeholder size=1080 %} 2x"
               alt=""
               class="img-fluid lazyload lazypreload">
        {% endif %}
      {% endwith %}
    </div>
    <button type="button" class="close modal-close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
      <span class="sr-only">{% trans "Close" %}</span>
    </button>
    <div class="col-md-7 col-12 product__info">
      <h1 class="product__info__name">
        {{ product.translated }}
      </h1>
      {% if user.is_staff %}
        <p>
          <a href="{% url "dashboard:product-details" pk=product.pk %}">
            {% trans "Edit in dashboard" context "Product details link text" %}
          </a>
        </p>
      {% endif %}
      {% if availability.available %}
        {% if show_variant_picker %}
          <div id="variant-price-component"></div>
          <script type="text/javascript">
            {% if LANGUAGE_CODE == "cs" %}
            jQuery(function($) {
              setTimeout(function(){
                {% if site.settings.display_gross_prices %}
                var VAT_INFO = "včetně DPH"
                {% else %}
                var VAT_INFO = "nezahrnuje DPH"
                {% endif %}
                $("#variant-price-component .product__info__price > small").text(VAT_INFO);
              }, 200);
            });
            {% endif %}
          </script>
        {% else %}
          <h2 class="product__info__price">
            <span>{% price_range availability.price_range %}</span>
            {% if availability.discount %}
              <small class="product__info__price__undiscounted">
                {% price availability.price_range_undiscounted %}
              </small>
            {% endif %}
            {% if availability.price_range_local_currency %}
              <br>
              <small class="text-info">
                &asymp;
                {% price availability.price_range_local_currency %}
              </small>
            {% endif %}
            {% if request.taxes %}
              <small>
                {% if site.settings.display_gross_prices %}

                {% else %}
                  
                {% endif %}
              </small>
            {% endif %}
          </h2>
        {% endif %}
      {% endif %}
      {% if is_visible and product.is_in_stock %}
        {% block orderform %}
          {% if show_variant_picker %}
            {% csrf_token %}
            <div id="variant-picker" data-variant-picker-data="{{ variant_picker_data }}" data-action="{% url 'product:add-to-checkout' product_id=product.pk slug=product.get_slug %}"></div>
          {% else %}
            <form id="product-form" role="form" class="product-form clearfix" method="post" action="{% url 'product:add-to-checkout' product_id=product.pk slug=product.get_slug %}" novalidate>
              {% csrf_token %}
              {% bootstrap_field form.variant %}
              <div class="product__info__quantity">
                {% bootstrap_field form.quantity %}
              </div>

              <div class="form-group product__info__button">
                <button class="btn primary">
                  {% trans "Add to cart" context "Product details primary action" %}
                </button>
              </div>
            </form>
          {% endif %}
        {% endblock %}
        <div class="form-group product__reserve__button">
          {% for variant in product.variants.all %}
          {% if variant.name == "originál" %}
          {% if variant.is_in_stock %}
          <a href="{% url 'theme_kotynkova:reserve_picture' product_id=product.pk slug=product.get_slug %}" class="btn btn-primary btn-block">
            {% trans "Reserve picture" context "Reserve picture primary action" %}
          </a>
          {% else %}
          <h3 class="text-danger">{% trans "This picture is already sold out." %}</h3>
          {% if product.variants.count > 0 %}
          <h3>{% trans "But you can choose from another variants." %}</h3>
          {% endif %}
          {% endif %}
          {% endif %}
          {% endfor %}
        </div>

        <div class="product__info__form-error">
          <small class="text-danger"></small>
        </div>
      {% else %}
        <p class="alert alert-warning">
          {% blocktrans context "Product details text" %}This product is currently <strong>unavailable</strong>.{% endblocktrans %}
        </p>
      {% endif %}
      {% if product.translated.description != " " %}
      <div class="product__info__description">
        <h3>{% trans "Description" context "Product details title" %}</h3>
        <hr>
        {{ product.translated.description|safe }}
      </div>
      {% endif %}
      <table>
        {% for attribute, value in product_attributes.items %}
        {% if attribute.slug == "format" %}
          <tr>
            <td>{{ attribute.translated }}:</td>
            <td><strong>{{ value.translated }} cm</strong></td>
          </tr>
         {% endif %}
        {% endfor %}
      </table>
    </div>
  </div>
  <script type="text/javascript">
    jQuery(function($) {
      function hideOriginalAmount() {
        if ($(".variant-picker__option.active").text() == "originál")
        {
          $(".form-group.product__info__quantity").hide();
          $(".product__info__price").css("visibility", "hidden");
          $("input#id_quantity").val(1);
          $("input#id_quantity").attr("value", 1);
          $(".product__reserve__button").show();
          $(".product__info__button").hide();
        }
        else
        {
          $(".form-group.product__info__quantity").show();
          $(".product__info__price").css("visibility", "visible");
          $(".product__reserve__button").hide();
          $(".product__info__button").show();
        }
      };
      // hide preloader
      setTimeout(function() {
        $(".preloader").fadeOut();
        $(".row.product").css("visibility", "visible");
      }, 600);
      // init detail
      setTimeout(function() {
        hideOriginalAmount();
        $(".variant-picker__option").click(function(){
          setTimeout(function(){
            hideOriginalAmount();
          }, 20);
        });
        getIndex = window.location.href.indexOf("?")
        if (getIndex != -1)
          getAndHash = window.location.href.substr(getIndex, window.location.href.length);
        $("body > .modal-close").click(function() {
          $("#modal-container .modal-close").trigger("click");
          $("#modal-container").html("");
          window.location.hash = "slick-slide-" + {{ product.id }};
        });
        // set active variant
        activeVariant = window.location.hash.replace("%20", " ").replace("%C3%97", "×").replace('%C3%A1', 'á').replace('%C4%8D', 'č').replace('%C3%AD', 'í').replace('%C5%99', 'ř');
        indexActive = activeVariant.indexOf("-act-");
        activeVariant = activeVariant.substr(indexActive+5, activeVariant.length);
        $(".btn.variant-picker__option").removeClass("active");
        $(".btn.variant-picker__option").map(function(){
          if ($(this).text() == activeVariant)
            $(this).find("input").trigger("click");
        });
        // bind escape to close modal
        $(document).keyup(function(e) {
          if(e.keyCode === 27)
            $("#modal-container .modal-close").trigger("click");
        });
      }, 200);
    });
  </script>
{% endblock modal_content %}

{% block modal_footer_scripts %}
  {% render_bundle 'storefront' 'js' %}
{% endblock modal_footer_scripts %}