saleor_theme_kotynkova/urls.py
from django.conf.urls import url
from . import views

app_name = 'theme_kotynkova'

urlpatterns = [
    url(r'^(?P<product_id>[0-9]+)/render-image/$',
        views.render_product_image, name="render_product_image"),
    url(r'^(?P<product_id>[0-9]+)/render-thumb/$',
        views.render_product_thumb, name="render_product_thumb"),
    url(r'^(?P<product_id>[0-9]+)/render-details/$',
        views.render_product_details, name="render_product_details"),
    url(r'^create-reservation/$',
        views.create_reservation, name='create_reservation'),
    url(r'^remove-reservation/$',
        views.remove_reservation, name='remove_reservation'),
    url(r'reservation/(?P<slug_id>[a-z0-9-_]+?)/$',
        views.reservation_details, name='reservation_details'),
    url(r'(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/reservation/$',
        views.reserve_picture, name='reserve_picture'),
]

saleor_theme_kotynkova/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings

from .conf import ReservationStatus


class Reservation(models.Model):
    slug_id = models.CharField(
        verbose_name=u"URL ID", max_length=150, default='')
    product_name = models.CharField("Product Name", max_length=386)
    product_id = models.IntegerField("Product ID")
    created = models.DateTimeField(
        default=timezone.now)
    status = models.CharField(
        max_length=32, default=ReservationStatus.RESERVED,
        choices=ReservationStatus.CHOICES)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='reservations',
        on_delete=models.CASCADE)
    note = models.TextField(max_length="500", blank=True, null=True)

    def get_absolute_url(self):
        return reverse('theme_kotynkova:reservation_details', kwargs={'slug_id': self.slug_id})

    class Meta:
        ordering = ('created', )

saleor_theme_kotynkova/templates/order/_ordered_items_table.html
{% load discount_as_negative from voucher %}
{% load i18n %}
{% load i18n_address_tags %}
{% load placeholder %}
{% load price from taxed_prices %}
{% load get_product_image_thumbnail from product_images %}
{% load display_translated_order_line_name from order_lines %}

{% if order.user == user %}
  <div class="order-details__addresses">
    <div class="row">
      {% if order.is_shipping_required %}
        <div class="col-6">
          <h3>
            <b>
              {% trans "Shipping address" context "Order details address title" %}
            </b>
          </h3>
          <hr class="margin-default" />
          {% format_address order.shipping_address %}
        </div>
      {% endif %}
      <div class="col-6">
        <h3>
          <b>
            {% trans "Billing address" context "Order details address title" %}
          </b>
        </h3>
        <hr class="margin-default" />
        {% format_address order.billing_address %}
      </div>
    </div>
  </div>
{% endif %}
<div class="table__header order-details__table-header d-none d-sm-block">
  <div class="row">
    <div class="col-md-8">
      <small>
        {% trans "Product" context "Order details column title" %}
      </small>
    </div>
    <div class="col-md-2 text-right">
      <small>
        {% trans "Quantity" context "Order details column title" %}
      </small>
    </div>
    <div class="col-md-2 text-right">
      <small>
        {% trans "Price" context "Order details column title" %}
      </small>
    </div>
  </div>
</div>

{% for line in order %}
  <div class="table__row order-details__product{% if forloop.last %} order-details__last-row{% endif %}">
    <div class="row">
      <div class="col-md-8 order-details__product__description">
        {% if line.variant %}
          <a class="link--clean" href="{% url 'product:category' slug=line.variant.product.category.slug category_id=line.variant.product.category.id %}#slick-slide-{{ line.variant.product.id }}">
            <img data-src="{% get_product_image_thumbnail line.variant.get_first_image size=60 method="thumbnail" %}"
                  data-srcset="{% get_product_image_thumbnail line.variant.get_first_image size=60 method="thumbnail" %} 1x, {% get_product_image_thumbnail line.variant.get_first_image size=120 method="thumbnail" %} 2x"
                  class="float-left lazyload lazypreload"
                  src="{% placeholder size=60 %}">
            <span>{% display_translated_order_line_name line %}</span>
          </a>
        {% else %}
          <img src="{% placeholder size=60 %}" class="float-left">
          <span>{% display_translated_order_line_name line %}</span>
        {% endif %}
      </div>
      <div class="col-md-4 order-details__product__description">
        <div class="row">
          <div class="col-md-6 col-12">
            <p class="text-right">
              <span>
                x {{ line.quantity }}
              </span>
            </p>
          </div>
          <div class="col-md-6 col-12">
            <p class="text-right">
              {% price line.get_total display_gross=order.display_gross_prices %}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

<div class="table__row">
  <div class="row">
    <div class="col-8 order-details__table-footer">
      <p>
        {% trans "Subtotal" context "Order details subtotal row text" %}
      </p>
    </div>
    <div class="col-4">
      <p class="float-right">
        {% price order.get_subtotal display_gross=order.display_gross_prices %}
      </p>
      <br>
    </div>
  </div>
</div>

{% if order.is_shipping_required %}
  <div class="table__row">
    <div class="row">
      <div class="col-8 order-details__table-footer">
        <p>
          {% trans "Shipping" context "Order details shipment row text" %} ({{ order.shipping_method_name|default:"-" }})
        </p>
      </div>
      <div class="col-4">
        <p class="float-right">
          {% price order.shipping_price display_gross=order.display_gross_prices %}
        </p>
      </div>
    </div>
  </div>
{% endif %}

{% if order.discount_amount %}
<div class="table__row">
  <div class="row">
    <div class="col-8 order-details__table-footer">
      <p>{{ order.translated_discount_name|default:order.discount_name }}</p>
    </div>
    <div class="col-4">
      <p class="float-right">
        {% discount_as_negative order.discount html=True %}
      </p>
    </div>
  </div>
</div>
{% endif %}

<div class="table__row">
  <div class="row">
    <div class="col-8 order-details__table-footer">
      <p>
        {% if order.display_gross_prices %}
          {% trans "Taxes (included)" context "Order details taxes text" %}
        {% else %}
          {% trans "Taxes" context "Order details taxes text" %}
        {% endif %}
      </p>
    </div>
    <div class="col-4">
      <p class="float-right">{% price order.total.tax %}</p>
    </div>
  </div>
</div>

<div class="order-details__total">
  <div class="row">
    <div class="col-8 order-details__table-footer">
      <div class="total">
        <h3>{% trans "Total" context "Order details total text" %}</h3>
      </div>
    </div>
    <div class="col-4">
      <p class="float-right">
        {% price order.total.gross %}
      </p>
    </div>
  </div>
</div>


{% for fulfillment in fulfillments %}
  <h2 class="order-details__header">
    {% blocktrans trimmed with fulfillment=fulfillment.composed_id context "Order details fulfillment title" %}
      Fulfillment #{{ fulfillment }}
    {% endblocktrans %}
  </h2>

  <div class="table__header order-details__table-header d-none d-sm-block">
    <div class="row">
      <div class="col-md-9">
        <small>
          {% trans "Product" context "Order details column title" %}
        </small>
      </div>
      <div class="col-md-3 text-right">
        <small>
          {% trans "Quantity" context "Order details column title" %}
        </small>
      </div>
    </div>
  </div>
  {% for fulfillment_line in fulfillment %}
    <div class="table__row fulfillment__row order-details__product{% if forloop.last %} order-details__last-row{% endif %}">
      <div class="row">
        <div class="col-md-6 col-9 order-details__product__description">
          {% with variant=fulfillment_line.order_line.variant %}
            {% if variant %}
              <a class="link--clean" href="{% url 'product:category' slug=product.category.slug category_id=product.category.id %}#slick-slide-{{ product.id }}">
                <span>{% display_translated_order_line_name fulfillment_line.order_line %}</span>
              </a>
            {% else %}
              <span>{% display_translated_order_line_name fulfillment_line.order_line%}</span>
            {% endif %}
          {% endwith %}
        </div>
        <div class="col-md-6 col-3">
          <p class="float-right">x {{ fulfillment_line.quantity }}</p>
        </div>
      </div>
    </div>
  {% endfor %}
  {% if fulfillment.tracking_number %}
    <div class="order-details__total">
      <div class="row">
        <div class="col-4 order-details__table-footer">
          <p>{% trans "Tracking number" context "Fulfillment tracking number details" %}</p>
        </div>
        <div class="col-8">
          <p class="float-right">{{ fulfillment.tracking_number }}</p>
        </div>
      </div>
    </div>
  {% endif %}
{% endfor %}

saleor_theme_kotynkova/templates/order/checkout_success.html
{% extends 'checkout/details.html' %}

{% load bootstrap_form from bootstrap4 %}
{% load staticfiles %}
{% load i18n %}
{% load placeholder %}

{% block title %}{% trans "Thank you" context "Checkout success page title" %} — {{ block.super }}{% endblock %}


{% block content %}
  <div class="row checkout__thankyoupage">
    <div class="col-md-8 m-auto">
      <img class="checkout__thankyoupage__parrot lazyload lazypreload" data-src="{% static 'images/confirm-order-bg.png' %}"
           srcset="{% static 'images/confirm-order-bg.png' %} 1x, {% static 'images/confirm-order-bg2x.png' %} 2x">
      <h1>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout title" %}
          Thank you for your <a href="{{ order_url }}">order</a>!
      {% endblocktrans %}</h1>

        <p>{% blocktrans trimmed with order_url=order.get_absolute_url context "Checkout text" %}
          We've sent a confirmation email with details to <span>{{ email }}</span>.<br>
          In case of any problems or questions please contact us.
        {% endblocktrans %}</p>
    </div>
    <div class="col-md-6 m-auto">
      <img class="checkout-pirate lazyload lazypreload" data-src="{% static 'images/checkout-bg.png' %}"
           srcset="{% static 'images/checkout-bg.png' %} 1x, {% static 'images/checkout-bg2x.png' %} 2x">
      <p><a href="{% url 'home' %}" class="btn secondary">
          {% trans "Continue shopping" context "Checkout secondary action" %}
      </a></p>
    </div>
  </div>
{% endblock %}

saleor_theme_kotynkova/templates/order/details.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load bootstrap_form from bootstrap4 %}

{% block title %}
  {% blocktrans trimmed context "Order details page title" %}
    Order {{ order }}
  {% endblocktrans %} — {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  {% if order.user == user %}
    <ul class="breadcrumbs list-unstyled">
      <li>
        <a href="{% url 'home'%}">
          {% trans "Home" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{% url "account:details" %}">
          {% trans "Your account" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{{ order.get_absolute_url }}">
          {% blocktrans trimmed context "Order details breadcrumb" %}
            Order {{ order }}
          {% endblocktrans %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock breadcrumb %}

{% block meta_tags %}
  <meta name="robots" content="noindex, nofollow">
{% endblock meta_tags %}

{% block content %}
<style>
.btn-secondary {
    color: #212529;
    background-color: #fff;
    border-color: #212529;
}
</style>
  {# This view is available by just knowing url,          #}
  {# so we don't show all details (like shipping address) #}
  {# unless current user is owner of the order.           #}
<div class="container">
  <div class="row order-details">
    <div class="col-lg-10 m-auto">
      <h2 class="order-details__header">
        {% blocktrans trimmed with order_status=order.get_status_display context "Order detail text" %}
          Order {{ order }}: {{ order_status }}
        {% endblocktrans %}
      </h2>
      {% if not order.is_fully_paid %}
        {% if order.is_pre_authorized %}
          <a href="{% url "order:payment" token=order.token %}" class="btn btn-link">
            {% trans "Payment details" context "Order details link text" %}
          </a>
        {% else %}
          <a href="{% url "order:payment" token=order.token %}" class="btn btn-primary">
            {% trans "Pay for order" context "Order details primary action" %}
          </a>
        {% endif %}
      {% endif %}
      {% include "order/_ordered_items_table.html" %}
      <div class="order-notes">
      {% if order.customer_note %}
        <h2 class="order-notes__header">{% trans "Your note" context "Customer order note" %}</h2>
        <p>{{ order.customer_note }}</p>
      {% endif %}
      {% if order.is_open and not order.customer_note %}
        <form method="post" class="form-group">
          {% csrf_token %}
          <h2>{% trans "Add a note to your order" context "Order note title" %}</h2>
          {% bootstrap_form note_form display_labels=False %}
          <input type="submit" value="{% trans 'Submit note' context 'Customer panel - order details: add note submit button' %}" class="btn btn-secondary" />
        </form>
      {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

saleor_theme_kotynkova/templates/order/payment.html
{% extends "base.html" %}

{% load bootstrap_form from bootstrap4 %}
{% load i18n %}
{% load static %}

{% block title %}
  {% blocktrans trimmed context "Payment details page title" %}
    Pay for order {{ order }}
  {% endblocktrans %} — {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  {% if order.user == user %}
    <ul class="breadcrumbs list-unstyled">
      <li>
        <a href="{% url 'home' %}">
          {% trans "Home" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{% url "account:details" %}">
          {% trans "Your account" context "Main navigation item" %}
        </a>
      </li>
      <li>
        <a href="{{ order.get_absolute_url }}">
          {% blocktrans trimmed context "Payment details breadcrumb" %}
            Order {{ order }}
          {% endblocktrans %}
        </a>
      </li>
    </ul>
  {% endif %}
{% endblock breadcrumb %}

{% block content %}
<div class="container">
  <div class="row checkout">
    <div class="col-lg-10 m-auto checkout__payment">
      {% if order.user == user or not order.is_fully_paid %}
        {% if not order.is_fully_paid and order.billing_address %}
          {% if waiting_payment %}
            <h1>
              {% trans "Payment pending" context "Payment details title" %}
            </h1>
            <form method="post" action="{% url 'order:cancel-payment' token=order.token %}" class="checkout-form">
              {% csrf_token %}
              <p>{% blocktrans trimmed context "Payment pending text" %}
                We are currently waiting for an external service to authorize
                your payment for this order.
              {% endblocktrans %}</p>
              <p>{% trans "Current status:" context "Payment status text" %}
                <br>
                <span class="label label-default">
                {{ waiting_payment.get_charge_status_display }}
                </span>
              </p>
              <p>{%  blocktrans trimmed context "Payment pending text" %}
                Unless you are absolutely sure that the process will not complete
                (for example you have closed the browser window before paying),
                you should wait before attempting a new payment.
                Please be warned that if you try again and the previous
                transaction succeeds you might end up being charged twice.
              {% endblocktrans %}</p>
              {% bootstrap_form waiting_payment_form %}
              <button type="submit" class="btn danger">
                {% trans "I understand, allow me to pay again" context "Payment pending action" %}
              </button>
            </form>
          {% elif payment_form %}
            <h1>
              {% blocktrans trimmed context "Payment details title" %}
                Pay for order {{ order }}
              {% endblocktrans %}
            </h1>
            <h3>
              <b>{% trans "Choose payment method" %}</b>
            </h3>
            <div class="checkout__payment-form">
              <form method="post" action="{% url "order:payment" token=order.token %}" class="payment-form radio">
                {% csrf_token %}
                {% for choice in payment_form.gateway %}
                  <div class="radio checkout__payment-form__choice">
                    <label>
                      <div class="card card-default">
                        <div class="card-body">
                          <strong>
                            {{choice}}
                          </strong>
                        </div>
                      </div>
                    </label>
                  </div>
                {% endfor %}
                {% block form_submit %}
                  <button type="submit" class="btn btn-primary">
                    {% trans "Proceed to payment" context "Payment details primary action" %}
                  </button>
                {% endblock %}
              </form>
            </div>
          {% else %}
            <p>{% trans "You've authorized transaction. Order is in processing" context "Payment details text" %}</p>
          {% endif %}
        {% endif %}
      {% endif %}
      {% include 'order/_ordered_items_table.html' %}
    </div>
  </div>
  <script>
    document.getElementById('id_gateway_0').nextSibling.textContent = "PayPal"
  </script>
</div>
{% endblock content %}

saleor_theme_kotynkova/templates/order/reservation.html
{% extends "checkout/index.html" %}
{% load i18n thumbnail %}
{% load bootstrap_form from bootstrap4 %}

{% block title %}{% trans "Reservation" %} - {{ site.name }}{% endblock %}

{% block content %}
<style>
.detail-img {
  cursor: pointer;
}
.modal .detail-img {
    margin: 0 auto;
    display: block;
}
</style>
<div class="container">
  <h1>{{ product.name }} - {% trans "Reservation" %} - <a class="btn btn-order" href="{% url 'product:category' slug=product.category.slug category_id=product.category.id %}#slick-slide-{{ product.id }}">{% trans "Back To Detail" %}</a></h1>
  <hr>
  <div class="row">
    <div class="col-md-5">
      {% thumbnail product.get_first_image.image "x600" format="PNG" crop="center" as image %}
      <img data-toggle="modal" data-target="#detailModalImage" class="img-fluid detail-img" src="{{ image.url }}">
      {% endthumbnail %}
      <hr>
      <ul>
        {% for attribute, value in product.get_product_attributes.items %}
        {% if attribute.slug == "format" %}
          <li> {{ attribute.translated }}: <strong>{{ value.translated }} cm</strong></li>
         {% endif %}
        {% endfor %}
      </ul>
      <!-- Modal -->
      <div class="modal fade" id="detailModalImage" tabindex="-1" role="dialog" aria-labelledby="detailModalImage" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="detailModalImage">{{ product.name }}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              {% thumbnail product.get_first_image.image "x900" crop="center" format="PNG" as image %}
              <img data-toggle="modal" data-target="#detailModalImage" class="img-fluid detail-img" src="{{ image.url }}">
              {% endthumbnail %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-7">
    {% for variant in product.variants.all %}
    {% if variant.name == "originál" %}
    {% if variant.is_in_stock %}
      {% if request.user.is_authenticated and not is_reserved %}
        <form id="product-reserve-form" role="form" class="product-reserve-form" method="post" action="{% url 'theme_kotynkova:create_reservation' %}">
          {% csrf_token %}
          <input name="product_id" type="hidden" value="{{ product.id }}">
          <input name="product_name" type="hidden" value="{{ product.name }}">
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="givenName">{% trans "Given Name" %}</label>
              <input name="given_name" type="text" class="form-control" value="{{ request.user.default_billing_address.first_name|default:'' }}" id="givenName" placeholder="{% trans "Given Name" %}" required="true">
            </div>
            <div class="form-group col-md-6">
              <label for="familyName">{% trans "Family Name" %}</label>
              <input name="family_name" type="text" class="form-control" value="{{ request.user.default_billing_address.last_name|default:'' }}" id="familyName" placeholder="{% trans "Family Name" %}" required="true">
            </div>
            <div class="form-group col-md-6">
              <label for="email">{% trans "Email" %}</label>
              <input name="email" type="email" class="form-control" value="{{ request.user.email|default:'' }}" id="email" placeholder="{% trans "Email" %}" required="true">
            </div>
            <div class="form-group col-md-6">
              <label for="phoneNumber">{% trans "Phone number" %}</label>
              <input name="phone_number" type="text" class="form-control" value="{{ request.user.default_billing_address.phone|default:'+420 ' }}" id="phoneNumber" placeholder="{% trans "Phone number" %}" required="true">
            </div>
            <div class="form-group col-md-12">
              <label for="comment">{% trans "Note" %}</label>
              <textarea name="note" class="form-control" rows="5" id="comment"></textarea>
            </div>
            <div class="form group col-md-12">
              <input id="consentCheck" type="checkbox" oninvalid="this.setCustomValidity('{% trans 'You must agree to the processing of personal data to submit this form.' %}')" onchange="this.setCustomValidity('')" required/>
              <label for="consentCheck">{% trans 'I agree to the processing of personal data.' %}</label>
            </div>
            <div class="form-group product__info__button col-md-6 m-auto">
              <button class="btn btn-primary">
                {% trans "Reserve picture" context "Reserve picture primary action" %}
              </button>
            </div>
          </div>
        </form>
      {% elif request.user.is_authenticated and is_reserved %}
      <p>{% trans "You have already created reservation to this picture." %}</p>
      <a class="btn btn-primary" href="{{ reservation.get_absolute_url }}">{% trans "View Reservation"%}</a>
      {% else %}
      <p>{% trans "You have to log in to create a new reservation." %}</p>
      <a class="btn btn-primary" href="{% url "account:login" %}?next={{ request.path }}">{% trans "Log In"%}</a>
      {% endif %}
    {% else %}
    <h3 class="text-danger">{% trans "This picture is already sold out." %}</h3>
    {% endif %}
    {% endif %}
    {% endfor %}
    </div>
  </div>
</div>
<br>
<br>
<br>
{% endblock content %}